prompts:
  - Explain the concept of {{topic}} in simple terms.
  - Write a short story about {{character}} in {{setting}}.
providers:
  - ollama:llama3.2:3b
  - ollama:gemma2:2b
  - ollama:qwen2:0.5b
tests:
  - description: Technical explanation
    vars:
      topic: quantum computing
      character: a scientist
      setting: a laboratory
  - description: Creative writing
    vars:
      topic: artificial intelligence
      character: a robot
      setting: the future
commandLineOptions:
  maxConcurrency: 2
  table: true
  verbose: true
